
# SEO settings
title: "Coin"
title2: "Algo" # default: ""
description: "Quant, data analysis and statistical models to discover better trading or investment strategies for cryptocurrencies."
keywords: "quant, data analysis, investment, altcoin, bitcoin, cryptocurrency"
url: http://coinalgo.com
# baseurl: "" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-100850555-1
repo: http://github.com/coinalgo/website
disqus_shortname: "CoinAlgo"
twitter_username: "nikhgupta"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Nikhil G."
  job      : "Cryptocurrency Enthusiast"
  bio      : "I run data analysis, quant and statistical models on cryptocurrency data to discover better trading or investment strategies."
  thumb    : /images/author.jpg
  email    : me@nikhgupta.com
  url      : http://coinalgo.com
  github   : http://github.com/coinalgo
  twitter  : http://twitter.com/nikhgupta
  facebook : https://www.facebook.com/nikhgupta
  linkedin : http://linkedin.com/in/mestoic

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@nikhgupta"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
